<?php

define('APL_DELEGATE_SEPARATOR', ':');

define('APL_LANGUAGE_PHP', 'php');

define('APL_DELEGATE_BASIC', 'basic');
define('APL_DELEGATE_CLASS', APL_DELEGATE_BASIC . APL_DELEGATE_SEPARATOR . 'class');
define('APL_DELEGATE_INTERFACE', APL_DELEGATE_BASIC . APL_DELEGATE_SEPARATOR . 'interface');

define('APL_DELEGATE_THEME_BASIC', 'theme');
define('APL_DELEGATE_THEME_CLASS_REF', APL_DELEGATE_THEME_BASIC . APL_DELEGATE_SEPARATOR . 'classref');
define('APL_DELEGATE_THEME_NAMESPACE', APL_DELEGATE_THEME_BASIC . APL_DELEGATE_SEPARATOR . 'namespace');
